# Generated by Django 5.0.4 on 2024-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='emp_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
